name: Build ESP-IDF Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' 

      - name: Set up ESP-IDF v4.4.5
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.5
          target: esp32

      - name: Build project
        run: |
          # Assuming sdkconfig is checked in and correct
          idf.py build

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin 
          # Optional: also upload other build outputs if needed
          # path: |
          #  build/*.bin
          #  build/flasher_args.json
          #  build/partition_table/partition-table.bin
          #  build/bootloader/bootloader.bin